[workspace]
members = ["folding-svg", "font-style"]
resolver = "2"


[workspace.dependencies]
log = "0.4.17"
custom-utils = "0.10.14"
floem = { git="https://github.com/jm-observer/floem.git", branch = "main-fork", features = ["editor", "serde", "default-image-formats", "rfd-async-std", "vger"], default-features = false }
